version: 2
updates:

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "sunday"
      time: "00:00"
      timezone: "Etc/UTC"
    assignees:
      - "bamalot"
      - "ldilley"
    reviewers:
      - "bamalot"
      - "ldilley"
    labels:
      - "task"
