# Travis CI build config for Concoct

language: c

os:
  - linux
  - osx

compiler:
  - clang
  - gcc

sudo: false

script:
  - mkdir bld
  - cd bld
  - cmake ..
  - make

notifications:
  email: false
