# Concoct AppVeyor config
version: 0.1.{build}
image: Visual Studio 2017
build_script:
  - mkdir build
  - cd build
  - cmake --version
  - cmake .. -G "Visual Studio 15 2017"
  - cmake --build . --target concoct --config Debug
  - bin\Debug\concoct.exe /v
on_success:
  - ps: Invoke-RestMethod https://raw.githubusercontent.com/DiscordHooks/appveyor-discord-webhook/master/send.ps1 -o send.ps1
  - ps: ./send.ps1 success $env:WEBHOOK_URL
on_failure:
  - ps: Invoke-RestMethod https://raw.githubusercontent.com/DiscordHooks/appveyor-discord-webhook/master/send.ps1 -o send.ps1
  - ps: ./send.ps1 failure $env:WEBHOOK_URL
notifications:
  - provider: GitHubPullRequest
    on_build_success: true
    on_build_failure: true
    on_build_status_changed: true
