name: Build

on: [push, pull_request]

jobs:
  basic:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]

    steps:
    - uses: actions/checkout@v3
    - name: CMake
      run: |
        pwd
        ls -la
        cd concoct
        mkdir bld
        cd bld
        cmake
        cd ..
        cmake --build bld --config Debug
